### PR TITLE
[state-machine] added rules for communication

### PR DESCRIPTION
**Pull request by sunava**
## Description
We have introduced new rules for communication and added visualization guidance in the "Serve Breakfast" challenge. These changes are aimed at fostering a more dynamic and less state-machine-dependent approach.

Communication Enhancements
Detailed Interaction: Robots are required to use specific and detailed language in their requests. Generic phrases like "please give me [object]" are unacceptable.
Example: A robot should say, "Please hand me the milk carton from the top-right shelf, third row," instead of a vague request.
Referee Role: Referees will enforce these communication standards strictly. Requests that lack specificity will be ignored.
Visualization Guidance
Perception Display: Robots must have a mechanism to display their internal perception data. This ensures referees can visually confirm what the robot is perceiving.

Closes issue #
Addresses issue: https://github.com/RoboCupAtHome/RuleBook/issues/805#issue-1829292526

Changes proposed in this pull request:
- {Specific Communication Guidelines}
- {Advanced Visual Perception Standards: }

## Other comments
This is only for one challenge; this guideline will be done for every challenge.

### CODE REVIEW

**Comment by LeroyR** [comment]
**Detailed Interaction:** Generic Phrases like that are already disallowed afaik. If this is not already handled with Rule `3.8 Deus Ex Machina`. We should just expand the rule if it is lacking in regard to unspecific language.

**Perception Display:** Is this even possible? Standard Platforms can not be modified and the screen is in the front of the robot -> Referee potentially blocks the robot during manipulation.
For OPL, i dont want to enforce any design but we could request that the Robot has a display at the back.

VizBox/custom external display has the obvious networking issues: communication error -> score penalty? Seems harsh as this is not influenced by the team. We dont want additional scoring discussions because the robot displays different images too quickly or the Referees missed something.

Some years ago we had Tasks where the Team/Robot had to produce a `pdf-report` afterwards, which feels like a better solution.

**Comment by sunava** [comment]
First, thank you for your feedback.

I've noticed that in the latest RoboCup, there were instances where referees provided items to robots even when the robots did not communicate as required. To address this, I propose we make it explicitly clear in the rules for each challenge what the specific communication requirements are. This will help ensure consistency in how referees respond to robot requests.

In particular, we should highlight that:

Robots must use detailed and specific language when requesting items.
Referees must adhere strictly to these guidelines and not respond to any requests that don't meet the specified criteria.
This approach will reinforce the importance of precise communication and ensure a fair and uniform standard across all challenges.

A few weeks ago, we discussed the possibility of allowing competitors to use the VizBox in our competitions. In the latest rulebook, the VizBox was actually a requirement, and several teams invested effort into supporting it. However, it turned out that the committee did not fully support this implementation.

After considering your suggestion, I find the idea of a PDF report more appealing than the VizBox or internal display approach. It seems like a more efficient and accessible way to handle the data presentation.

On that note, are there any existing rules or guidelines regarding the use of PDF reports? If there's a document or a set of standards about this, it would be helpful to review them to better understand how we can integrate this method into our competition.

**Comment by sunava** [comment]
Closing this PR after talking to Alex, Leroy and Juan about it. -> I will look into a template of a pdf report.

**Comment by ARTenshi** [comment]
Before closing this one, as a reminder, the PDF file was removed because it was more of a problem than a solution. First, there wasn't a standard format (among teams or tasks), and it was a burden for the referees to check every PDF after the slots and to remember what had happened; also, the PDF might not coincide with the reality -- while the PDF recognition might be correct, the robot might have taken the wrong object (especially when the objects are too close) and, especially with partial points, teams tend to reclaim points long after the task frame has finished.

**Pull request closed without merging**
