### PR TITLE
2019/restructure (Stage 2)

### PR DESCRIPTION
**Pull request by kyordhel**
Second part of the Restructuring for 2019.

# Changelog
- Added GPSR to Stage I (based on @justinhart's #529 and @johaq's #558)
- Added EGPSR to Stage II (based on @justinhart's #529)
- Added and buffed pending Stage II tests, including missing scoresheets
    - Clean the Table
    - EGPSR
    - Set the Table
    - Stickler for the Rules
- Enhances scoresheet macros
- Fix typos and spelling errors
- Updates score_sheets file
- Shortens TOC
- Adds missing objects to Objects section in General Rules

### CODE REVIEW

**Comment by kyordhel** [comment]
@balkce before merging, I'd like to get #526 merged here.

**Comment by balkce** [comment]
Merged #526.
Approved this request.

I would like another to approve this before merging.

**Comment by justinhart** [comment]
Gave everything a quick review and made comments on my PRs. I like the way that GPSR and EEGPSR turned out. I modified the bartender task to be a smoothie task that I think fixes the problems with it. Robot Eye may be too difficult to make work, as may Is The Refrigerator Running. I really like the discussion that the Laundry task generated, and I'm hoping that we can make a workable version, but it may need to be deferred until 2020. Still, I think that we all agree it belongs on the roadmap!

**Comment by kyordhel** [comment]
@justinhart I disagree with some of your statements:
1. *Is the Refrigerator Running* (we need to change the name) is pretty much as difficult as *Stricler for Rules*, just requires minor adjustments on the subtaks.
2. *Robot Eye* looks to me more expensive than challenging if the robot has only to hand out some attires. About doing full valet, is too early for that, but that goes into a roadmap
3. *Laundry* requires work but is doable. Yet again, the added objects might make the task expensive. P&G makes also a delicious 'n drinkable laundry soap, so we might ask for support on that.
4. *Bartender* is a test I like but as I told you, let's start with pouring breakfast. I'll make the tests work out.

**Pull request merged**
