### PR TITLE
REMOVE: Serve Breakfast task

### PR DESCRIPTION
**Pull request by moriarty**
## Description

We need to reduce the number of tasks.
- 7 teams opted into this task
- 2 attempted this task in Sydney
- 0 teams scored on this task

## Other comments
At least a few of the @RoboCupAtHome/technical-commmittee needs to agree on this, and maybe if needed discuss it. But otherwise it's ready to merge as soon as you've talked about it.

### CODE REVIEW

**Comment by moriarty** [comment]
@johaq this was discussed in the meeting, do you want to merge it?

**Comment by moriarty** [comment]
@jahaq & TC how’s the progress on cutting down the RuleBook?

**Comment by nickswalker** [comment]
I think the plan is to talk about the couple places where people disagreed in #685 and finalize the cuts during the next meeting

**Comment by johaq** [comment]
Yes, we will decide in the next meeting. You can see the date and add to tops here:
https://docs.google.com/document/d/1TA31QM7BXq_wb_AIPh4SnOXCWeGsRtua2bAqmqdkfnE/edit

**Comment by moriarty** [comment]
From google doc @johaq linked to:

1. Everyone fine with Storing Groceries?
2. Clean Up vs Take out the Garbage
    - Proposal: add element of clean up to take out the garbage
3. Everyone fine with Carry my Luggage?
4. Receptionist vs Serving Drinks vs Find my Mates vs Hand me That (shift from Stage 2) vs Where is This (shift from Stage 2)
5. Everyone fine with Clean the Table?
6. New vs Hand me That

Serve the Breakfast isn't up for the vote, so I think this can be merged.

**Pull request merged**
