### PR TITLE
Modified GPSR to fit Stage 1

### PR DESCRIPTION
**Pull request by johaq**
1. Only 3 commands
2. Distinguish between task and commands
3. Only one operator to keep already complicated setup manageable
4. One location for the robot to receive commands

### CODE REVIEW

**Comment by kyordhel** [comment]
@johaq  please `git pull --rebase` before pushing anything else

**Comment by johaq** [comment]
Yeah sorry. Had this stored a while ago and did not update. 
This is meant to move gpsr from stage 2 to stage 1. So i removed gpsr from stage 2 now.

**Comment by kyordhel** [comment]
Can we keep both? GPSR in Stage I and EGPSR in Stage II?

**Comment by kyordhel** [comment]
@johaq I'm stealing your mods and incorporating both tests.

Will push them directly.

**Pull request closed without merging**
