### PR TITLE
Split rulebook

### PR DESCRIPTION
**Pull request by PetervDooren**
** Note: Your contribution is expected to meet the conventions and policies described in the [contribution guidelines](https://github.com/RoboCupAtHome/RuleBook/wiki/Guidelines:-Contributing) **
Made to replace #829 

## Description
Splits rulebook into the rules and organization of the competition. This makes for a briefer rulebook and hopefully a better intro for new teams.

Closes issue #

Changes proposed in this pull request:
- split rules and organization into two documents
-
-

## Other comments
If this request is marked as a draft, please describe your plans or any specific feedback you would like

Todo:

- [x] Edit the documents to be legible on their own.

### CODE REVIEW

**Review by akinobu1998 — APPROVED** [review]
Great, this is a minor suggestion.
What if we have a different title page for Rules and Organization to distinguish both documents easily?

**Comment by MatthijsBurgh** [comment]
The splitted rulebook should be generated by the CI before merging this PR.

**Review by johaq — DISMISSED** [review]
Good idea and good execution as far as I can see. 
Agree with @MatthijsBurgh about CI compatibility but otherwise good to go.

**Comment by YuqianJiang** [comment]
Looks good

**Review by YuqianJiang — DISMISSED** [review]

**Review by akinobu1998 — APPROVED** [review]

**Review by MatthijsBurgh — CHANGES_REQUESTED** [review]
The PDF title & subject of the new organization file is incorrect. As it includes `setup/config.tex`, which is designed for the rulebook. Please change this and check all the copy-pasting didn't cause any other similar issues.

**Comment by MatthijsBurgh** [comment]
You created `Orgnazation.tex` with capital letter again...

**Review by LeroyR — APPROVED** [review]

**Comment by MatthijsBurgh** [comment]
I think we should add the Roadmap document as well. I will try to add it within 1 week.

**Review by YuqianJiang — APPROVED** [review]
Looks great!

**Comment by MatthijsBurgh** [comment]
The roadmap document is not compiled yet....

**Pull request merged**
