### PR TITLE
Remove Open Challenge, Finals and other

### PR DESCRIPTION
**Pull request by maximest-pierre**
** Note: Your contribution is expected to meet the conventions and policies described in the [contribution guidelines](https://github.com/RoboCupAtHome/RuleBook/wiki/Guidelines:-Contributing) **

## Description

Closes issue #

Changes proposed in this pull request:
- Remove Open Challenge
- Remove Finals
- Reduce the number of tests
- Add simulation platform

### CODE REVIEW

**Comment by moriarty** [comment]
FYI for everyone I've tagged as reviewers:

get_rulebook

**Review by kyordhel — APPROVED** [review]

**Comment by moriarty** [comment]
@maximest-pierre great start, and this could be merged as is... or you can continue to cut the first 30 pages.

I don't know if there needs to be two stages and three tests. Given the simulator is Gazebo under the hood, I would cut `What is That?` task all together.

Tidy Up, would work well in sim.
Storing Groceries will work well in sim.
What is That, is a bit tricky to do in sim due to the HRI aspect

**Comment by moriarty** [comment]
@maximest-pierre add a linke to this simulation environment which wraps gazebo: 
https://github.com/hsr-project/tmc_wrs_docker

**Comment by moriarty** [comment]
@maximest-pierre @RoboCupAtHome/technical-commmittee & @RoboCupAtHome/organizing-comittee anyone have time to give this a lookover?

@maximest-pierre it's still marked as a draft PR but it looks reasonable.

**Review by MatthijsBurgh — DISMISSED** [review]

**Review by moriarty — APPROVED** [review]

**Review by nickswalker — DISMISSED** [review]
Reasonable changes :+1:

**Pull request closed without merging**
