### PR TITLE
External speakers DSPL

### PR DESCRIPTION
**Pull request by LarsJanssenTUe**
As discussed in #626.
Any remarks and or changes are welcomed!

### CODE REVIEW

**Comment by kyordhel** [comment]
I'd kindly request you **not to modify this rule**.

I think is better to leave it lean and simple. Instead, please ad an *DSPL allowed add-ons* below the backpack specification.

**Comment by kyordhel** [comment]
@MatthijsBurgh please check #635

**Comment by balkce** [comment]
> I'd kindly request you **not to modify this rule**.
> 
> I think is better to leave it lean and simple. Instead, please ad an _DSPL allowed add-ons_ below the backpack specification.

Agreed.

**Comment by MatthijsBurgh** [comment]
As #635 is merged, this PR can be closed.

**Pull request closed without merging**
