### PR TITLE
Networking set up

### PR DESCRIPTION
**Pull request by LoyVanBeek**
See #173

### CODE REVIEW

**Comment by tik0** [comment]
Here you assume, that every team shares the same physical switch and (wireless-) network, right?
Shouldn't we even go a step further:

- Setup a vlan for every team to have at least a logical separation
  - This is absolutely necessary due to the promiscues and unsecure software  (ROS, etc.) the teams are using
  - With a vlan, every team can setup their own IP range and even DHCP servers
- WLAN setup
  - The APs should promote a unique SSID for every team, which then routes to the specific vlan
  - This has the nice benefit of switching the SSIDs on/off for the corresponding teams in the current task
- Punishment and fall-back
  - There should be some punishment for not obeying the rule, that a team has to use the official network
  - A decision at the **end of the first setup day** should be made, if the official network is usable for all teams, or not. And if not, are the teams allowed to use their own WLAN and network?
  - If we think practical, the upper point answers it self: Different teams come from different countries, which allows only particular WLAN frequency channels which might not work with the local setup. Thus, if one team is **technically** unable to use the official WLAN, then no one needs to use it, which leads to the question: Is it possible to setup and support an official network/WLAN/VLAN?

**Comment by LoyVanBeek** [comment]
Hi @tik0, good points made there. The setup as it is now is mimicked from the Middle Size League. They can do it and we should be able as well. 

I totally agree on the decision on the end of the first setup day. 

VLANs sound very useful, but I'm not a network administrator and my networking knowledge is not that deep. I asked the OC for some detail yesterday on how they plan to do things. 
If we can use DD-WRT on the wireless routers, VLANs should possible. I'm not sure whether multiple SSIDs is possible on a single channel as well. 

Preferably, there's a person who can arrange and manage this for us :smiley:

**Comment by semeyerz** [comment]
Despite VLANs/Unique BSSIDs are a great idea, we have to decide whether we want to provide Internet and be able to have a Referee-Box soon.

If so it could be quite hard to set up routing to the web and to the ref-box if teams share the same IP-Adresses even in different VLANs.
Teams are allowed to announce external computing they should be able to access Internet from the wifi.
This means we should assign ip-ranges now even if we are able to get a good vlan setting running that separates the teams from each other.

**Comment by LoyVanBeek** [comment]
So, we had a chat about the @Home network today, the TC (me) and some people of Homer, TechUnited and ToBi. 

The setup decided on is using a VLAN with a managed switch:

- The teams register the MAC addresses of their WiFi-enabled devices: with a reasonable max per team. We will not register all the team laptops, just the bare minimum: their robot(s) and 1 or 2 laptops and perhaps a tablet. 
- There is a central switch, with ca. 40 Gigabit ethernet ports
- Each arena has a wireless access point with its own SSID
- From the central switch, there goes 1 cable to each team table. They can do whatever they want on that cable. Everything on that cable (so of that particular team) always gets routed to the MAC-addresses associated with that team, via a Virtual LAN. 
- The refbox (to be, in the future) is also connected to every VLAN so all the teams can access it. 
- Teams teams can put  a switch, router with DHCP server on their table and plug the cable from the central switch into it. And also plug a different cable with internet access into the same router. 

For this, we'll need a managed switch, with the following requirements:

1. VLAN-capable
2. 40 ports or so
3. Perhaps a firewall to limit internet access of the robots

The estimated cost of such a thing is in the 5000-10000 euro range.

**Comment by rventura** [comment]
The network setup proposal looks great. I'd only advise to make sure the WiFi APs are capable of segregating different MAC addresses to different VLANs. It should be the AP to split traffic among different VLANs, not the switch (that'd be too late).

**Pull request closed without merging**
